import type { Voila } from "../types/voila/index"

export const product: Voila.Product = {
	productId: "123456789",
	retailerProductId: "R123456789",
	type: "GROCERY",
	name: "Organic Whole Milk",
	brand: "Happy Cow",
	packSizeDescription: "1L",
	price: {
		amount: "3.50",
		currency: "CAD",
	},
	unitPrice: {
		price: {
			amount: "0.35",
			currency: "CAD",
		},
		unit: "100ml",
	},
	available: true,
	isVerifiedPurchase: false,
	quantityInBasket: 0,
	maxQuantityReached: false,
	promotions: [
		{
			promoId: "PROMO1",
			retailerPromotionId: "RPROMO1",
			description: "2 for $6.00",
			type: "MULTIBUY",
			presentationMode: "REGULAR",
			limitReached: false,
		},
	],
	taxCodesDisplayNames: ["HST"],
	promoPrice: {
		amount: "3.00",
		currency: "CAD",
	},
	promoUnitPrice: {
		price: {
			amount: "0.3",
			currency: "CAD",
		},
		unit: "l00ml",
	},
	imageConfig: {
		availableFormats: ["webp", "jpeg"],
		availableResolutions: ["100", "200", "400"],
	},
	image: {
		src: "/images/123456789.webp",
		description: "A carton of Happy Cow Organic Whole Milk",
		fopSrcset: "/images/123456789-fop.webp",
		bopSrcset: "/images/123456789-bop.webp",
		imageId: "IMG123",
	},
	images: [
		{
			src: "/images/123456789.webp",
			description: "A carton of Happy Cow Organic Whole Milk",
			fopSrcset: "/images/123456789-fop.webp",
			bopSrcset: "/images/123456789-bop.webp",
			imageId: "IMG123",
		},
	],
	imageIds: ["IMG123"],
	imagePaths: ["/images/123456789.webp"],
	iconAttributes: [
		{
			label: "Organic",
			file: "organic-icon.svg",
		},
	],
	icons: [],
	basketLines: [],
	timeRestricted: false,
	alternatives: [],
	isInShoppingList: false,
	isInCurrentCatalog: true,
	retailerFinancingPlanIds: [],
	alcohol: false,
	categoryPath: ["Dairy & Eggs", "Milk", "Organic Milk"],
	isNew: false,
}

export const dataLayerFixture = {
	event: "view_item_list",
	ecommerce: {
		currency: "CAD",
		items: [
			{
				item_id: "182792EA",
				item_name: "Oasis Juice Orange Pure Breakfast 960 ml",
				index: 15,
				item_brand: "Oasis",
				hfss_display_restriction_group: null,
				item_list_name: "promotions: on-offer",
				item_variant: "960ml",
				price: 2.79,
				rating: null,
				quantity: 1,
				is_on_promotion: true,
				promotion_ids:
					"1000175010_1ea250ca-1254-4784-8954-d512d1ede85d",
				is_favorite: false,
				is_featured: false,
				featured_campaign_id: null,
				featured_campaign_name: null,
				can_add_to_cart: true,
				item_category: "Beverages",
				item_category2: "Fruit & Vegetable Juice",
				item_category3: "Orange Juice",
				seller_id: null,
			},
			{
				item_id: "433830CS",
				item_name:
					"Coca-Cola Soda Fridge Pack 12 x 355 ml (cans)",
				index: 16,
				item_brand: "Coca-Cola",
				hfss_display_restriction_group: null,
				item_list_name: "promotions: on-offer",
				item_variant: "12 x 355ml",
				price: 8.99,
				rating: null,
				quantity: 1,
				is_on_promotion: true,
				promotion_ids:
					"7628192_c44ef765-f1a0-416f-85d2-a9dfae55cb83",
				is_favorite: false,
				is_featured: false,
				featured_campaign_id: null,
				featured_campaign_name: null,
				can_add_to_cart: true,
				item_category: "Beverages",
				item_category2: "Soft Drinks",
				item_category3: "Cola",
				seller_id: null,
			},
			{
				item_id: "276370EA",
				item_name: "Maple Leaf Natural Bacon Original 375 g",
				index: 17,
				item_brand: "Maple Leaf",
				hfss_display_restriction_group: null,
				item_list_name: "promotions: on-offer",
				item_variant: "375g",
				price: 8.99,
				rating: null,
				quantity: 1,
				is_on_promotion: true,
				promotion_ids:
					"92502_71c9ffde-fcb7-40be-b4d4-cee11d6dda37",
				is_favorite: false,
				is_featured: false,
				featured_campaign_id: null,
				featured_campaign_name: null,
				can_add_to_cart: true,
				item_category: "Meat & Seafood",
				item_category2: "Bacon",
				item_category3: "Pork Bacon",
				seller_id: null,
			},
			{
				item_id: "130324EA",
				item_name: "Compliments Basil 20 g",
				index: 18,
				item_brand: "Compliments",
				hfss_display_restriction_group: null,
				item_list_name: "promotions: on-offer",
				item_variant: "20g",
				price: 2.49,
				rating: null,
				quantity: 1,
				is_on_promotion: true,
				promotion_ids:
					"92572_a7befd7c-e389-43fe-b32d-343cfc0a4a56,7531936_0e557094-4750-4803-861b-74542bfc9efc",
				is_favorite: false,
				is_featured: false,
				featured_campaign_id: null,
				featured_campaign_name: null,
				can_add_to_cart: true,
				item_category: "Fresh Fruits & Vegetables",
				item_category2: "Fresh Herbs",
				seller_id: null,
			},
			{
				item_id: "38004EA",
				item_name: "GoodLeaf Cool Crisp Lettuce 113 g",
				index: 19,
				item_brand: "GoodLeaf",
				hfss_display_restriction_group: null,
				item_list_name: "promotions: on-offer",
				item_variant: "113g",
				price: 3.99,
				rating: null,
				quantity: 1,
				is_on_promotion: true,
				promotion_ids:
					"92572_dbbfd195-beb6-4661-9753-8fa634595dd5",
				is_favorite: false,
				is_featured: false,
				featured_campaign_id: null,
				featured_campaign_name: null,
				can_add_to_cart: true,
				item_category: "Fresh Fruits & Vegetables",
				item_category2: "Fresh Packaged Salads & Dressing",
				item_category3: "Fresh Salad Kits & Mixes",
				seller_id: null,
			},
		],
	},
	"gtm.uniqueEventId": 87,
}

export const decoratedProduct: Voila.DecoratedProduct = {
	productId: "",
	retailerProductId: "",
	type: "",
	name: "",
	brand: "",
	packSizeDescription: "",
	countryOfOrigin: "",
	seller: "",
	isNew: false,
	price: {
		amount: 0,
		currency: "",
	},
	grossPrice: 0,
	unitPrice: {
		price: {
			amount: 0,
			currency: "",
		},
		unit: "",
		pricePerSuffix: "",
	},
	referencePrice: 0,
	depositPrice: 0,
	additionalProductCharge: 0,
	promoPrice: {
		amount: 0,
		currency: "",
	},
	promoUnitPrice: {
		price: {
			amount: 0,
			currency: "",
		},
		unit: "",
		pricePerSuffix: "",
	},
	promotions: [],
	unavailablePromotions: [],
	favorite: null,
	regular: null,
	available: false,
	isVerifiedPurchase: false,
	quantityInBasket: 0,
	maxQuantityReached: false,
	quantityRestrictionGroup: null,
	maxAvailableQuantity: 0,
	alternatives: [],
	isInShoppingList: false,
	isInCurrentCatalog: false,
	ratingSummary: null,
	restrictedVisibility: null,
	verifyMode: null,
	categoryPath: [],
	retailerFinancingPlanIds: [],
	hfssDisplayRestrictionGroup: null,
	medicalQuestionnaireRequired: null,
	taxCodesDisplayNames: [],
	imageConfig: {
		availableFormats: [],
		availableResolutions: [],
	},
	image: {
		src: "",
		description: "",
		fopSrcset: "",
		bopSrcset: "",
		imageId: "",
	},
	images: [],
	imageIds: [],
	imagePaths: [],
	iconAttributes: [],
	icons: [],
	basketLines: [],
	ageRestriction: null,
	alcohol: false,
	catchweight: null,
	guaranteedProductLife: null,
	temperatureRegime: null,
	timeRestriction: null,
	timeRestricted: false,
	checkoutTimeRestriction: null,
	checkoutTimeRestricted: null,
	deliveryTimeRestrictionMessage: "",
	checkoutTimeRestrictionMessage: "",
}

export const fetchPromotionPageResponse: Voila.FetchPromotionPageResponse =
	{
		productGroups: [
			{
				decoratedProducts: [],
			},
		],
		metadata: {},
	}

export const fetchProductsResponse: Voila.FetchProductsResponse =
	{
		products: [
			product,
			{
				...product,
				productId: "987654321",
				name: "Organic 2% Milk",
				brand: "Beatrice",
				packSizeDescription: "250ml",
			},
		],
		missedPromotions: [],
		restrictedGroups: {},
	}
export const addToCartResponse: Voila.AddToCartResponse = {
	basketUpdateResult: {
		items: [],
		lastModified: "",
		totals: {
			itemsRetailPrice: {
				amount: "",
				currency: "",
			},
			itemPriceAfterPromos: {
				amount: "",
				currency: "",
			},
			savingsPrice: {
				amount: "",
				currency: "",
			},
			taxation: "",
			display: {
				itemPriceAfterPromos: {
					amount: "",
					currency: "",
				},
				taxation: "",
			},
			itemPriceAfterPromosDifference: {
				amount: "",
				currency: "",
			},
		},
		itemGroups: [],
	},
	unavailableData: [],
	pricingNotifications: [],
	limitedItems: [],
	limitedPromotionIds: [],
}
